#!/bin/sh
#SBATCH --job-name=nasa-roses-uva
#SBATCH --ntasks=1
#SBATCH --time=02:00:00
#SBATCH --mail-type=end,fail,requeue
#SBATCH --mail-user=smxnv@mst.edu
#SBATCH --export=all
#SBATCH --mem=100G
#SBATCH --out=HydroMAP-Foundry-%j.out


 python uva_roses.py \
 --input-shp '../Data/gis shapefiles/nga_admbnda_adm2_osgof_20190417.shp' \
 --load-files True \
 --output-dir ../Outputs/ \
 --start-year 2012 \
 --end-year 2021 \
 --data-list All \
 --target-res 1000 \
 --gdal-path /usr/bin/gdal/
